### ISSUE TITLE
README suggestions

### ISSUE THREAD

**Issue by ValdezBalderas** [fastforwardlabs/continuous-monitoring#5]
### README

At the very end of the README file, an instruction reads: 

> As an AMP - In a CML workspace, click "New Project", add a Project Name, select "ML Prototype" as the Initial Setup option, copy in this repo URL, click "Create Project", click "Configure Project"

- [x] I couldn't find an "ML Prototype".  

- [x] It could be helpful to indicate in the README file if the default configuration values (shown below) are OK and all the user has to do is to click "Launch Project". Or if that's not necessarily the case for all users (perhaps those with scarce resources), then to say how and why to change those values. 

<img width="810" alt="Screen Shot 2022-01-21 at 10 58 31 AM" src="https://user-images.githubusercontent.com/28984461/150576879-e16ad6a5-c057-4604-92c8-2e1c09f9b844.png">

- [x] The README lists 4 steps, but the AMP Setup lists 7 steps. Would it make sense to include the three remaining steps in the README?

- [x] Have you thought about using a figure more descriptive of what the AMP does? Perhaps a monitoring plot or something from the output? Or something that that indicates the combined use of CML Metrics + Evidently.ai  ?

**Comment by andrewrreed** [comment]
Thanks for this feedback @ValdezBalderas!

> I couldn't find an "ML Prototype".

Good catch - the UI has been updated and now says "AMPs". I updated the README accordingly

> It could be helpful to indicate in the README file if the default configuration values (shown below) are OK...

These values are actually pre-populated based on what's specified in the `.project-metadata.yaml` file. If a user's workspace doesn't have image or resources that are specified, there's actually a warning message that pops up in the UI that lets the user know.

> The README lists 4 steps, but the AMP Setup lists 7 steps. Would it make sense to include the three remaining steps in the README?

I see how this could be confusing since I use the word "steps". The issue is that the one logical "step" of deploying the model is actually broken out into 3 specified steps (create model, build model, deploy model) - this is just how the AMPs feature was designed. With that, I did add a line to the README to indicate the step that installs dependencies.

> Have you thought about using a figure more descriptive of what the AMP does?

Yes! I'm actually working on a custom UI that will serve as a better interface for the project. Once I have that completed, I'll replace the generic "Evidently.ai" logo with a screenshot of the UI. (see below for sneak peek of that UI - WIP)

![image](https://user-images.githubusercontent.com/23462538/150843465-c5640aeb-07e2-4c90-a873-023fac45eae8.png)
